# Generated by Django 2.1.3 on 2018-11-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=32)),
                ('wework_id', models.CharField(default='', max_length=128)),
                ('avatar_url', models.CharField(default='', max_length=1024)),
                ('sex', models.CharField(default='未设置', max_length=4)),
            ],
        ),
    ]
