# Generated by Django 2.1.3 on 2018-11-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_wechat', '0006_auto_20181120_2042'),
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wework_id',
        ),
        migrations.AddField(
            model_name='user',
            name='enterprise_wechat_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='enterprise_wechat.EnterpriseWechatUser'),
        ),
    ]
