# Generated by Django 2.1.3 on 2018-11-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseWechatAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024)),
                ('expire_in', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseWechatApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_id', models.CharField(max_length=1024)),
                ('corp_secret', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='enterprisewechataccesstoken',
            name='enterprise_wechat_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise_wechat.EnterpriseWechatApp'),
        ),
    ]
