# Generated by Django 2.1.3 on 2018-11-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisewechatapp',
            name='agent_id',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
