# Generated by Django 2.1.3 on 2018-11-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_wechat', '0002_enterprisewechatapp_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisewechatapp',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
