# Generated by Django 2.1.3 on 2018-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_wechat', '0005_enterprisewechatuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisewechatuser',
            name='user_id',
            field=models.CharField(max_length=128),
        ),
    ]
