# Generated by Django 2.1.3 on 2018-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_switch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotpi',
            name='type_id',
        ),
        migrations.AddField(
            model_name='robotpi',
            name='type_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
